# Generated by Django 6.0.3 on 2026-04-01 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISOControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('norm', models.CharField(choices=[('27001', 'ISO 27001'), ('27002', 'ISO 27002'), ('27005', 'ISO 27005')], default='27002', max_length=10)),
                ('category', models.CharField(choices=[('politique', 'Politique de Sécurité'), ('organisation', 'Organisation de la Sécurité'), ('rh', 'Sécurité des RH'), ('actifs', 'Gestion des Actifs'), ('acces', "Contrôle d'Accès"), ('cryptographie', 'Cryptographie'), ('physique', 'Sécurité Physique'), ('operations', 'Sécurité Opérationnelle'), ('communications', 'Sécurité des Communications'), ('incidents', 'Gestion des Incidents'), ('continuite', "Continuité d'Activité"), ('conformite', 'Conformité')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('guidance', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contrôle ISO',
                'verbose_name_plural': 'Contrôles ISO',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('hopital', 'Hôpital / Santé'), ('ecommerce', 'E-Commerce'), ('entreprise', 'Entreprise de Services'), ('banque', 'Banque / Finance'), ('industrie', 'Industrie / Manufacturing')], max_length=50)),
                ('difficulty', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='intermediaire', max_length=20)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('company_context', models.TextField()),
                ('audit_objective', models.TextField()),
                ('icon', models.CharField(default='🏢', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scénario',
                'verbose_name_plural': 'Scénarios',
            },
        ),
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.scenario')),
            ],
            options={
                'verbose_name': "Session d'Audit",
                'verbose_name_plural': "Sessions d'Audit",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.isocontrol')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_controls', to='audit_app.scenario')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'control')},
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('evidence_type', models.CharField(choices=[('document', 'Document / Politique'), ('config', 'Configuration Système'), ('log', 'Extrait de Log'), ('interview', 'Compte-rendu Entretien'), ('observation', 'Observation Terrain')], max_length=20)),
                ('content', models.TextField()),
                ('hint', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non Conforme'), ('partiel', 'Partiellement Conforme')], max_length=20)),
                ('scenario_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='audit_app.scenariocontrol')),
            ],
            options={
                'verbose_name': 'Preuve',
                'verbose_name_plural': 'Preuves',
            },
        ),
        migrations.CreateModel(
            name='ControlEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conformity', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non Conforme'), ('partiel', 'Partiellement Conforme'), ('na', 'Non Applicable')], max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('critique', 'Critique')], max_length=10)),
                ('risk_probability', models.IntegerField(default=1, help_text='1-5')),
                ('risk_severity', models.IntegerField(default=1, help_text='1-5')),
                ('recommendation', models.TextField(blank=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_evaluations', to='audit_app.auditsession')),
                ('evidences_consulted', models.ManyToManyField(blank=True, to='audit_app.evidence')),
                ('scenario_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.scenariocontrol')),
            ],
            options={
                'verbose_name': 'Évaluation de Contrôle',
                'verbose_name_plural': 'Évaluations de Contrôle',
                'unique_together': {('session', 'scenario_control')},
            },
        ),
    ]
