# Generated by Django 6.0.3 on 2026-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlevaluation',
            options={'verbose_name': 'Evaluation de Controle', 'verbose_name_plural': 'Evaluations de Controle'},
        ),
        migrations.AlterModelOptions(
            name='isocontrol',
            options={'ordering': ['code'], 'verbose_name': 'Controle ISO', 'verbose_name_plural': 'Controles ISO'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='icon',
        ),
        migrations.AddField(
            model_name='controlevaluation',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenario',
            name='sector_icon',
            field=models.CharField(default='E', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Termine')], default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='controlevaluation',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Eleve'), ('critique', 'Critique')], max_length=10),
        ),
        migrations.AlterField(
            model_name='controlevaluation',
            name='risk_probability',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='controlevaluation',
            name='risk_severity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('document', 'Document / Politique'), ('config', 'Configuration Systeme'), ('log', 'Extrait de Log'), ('interview', 'Compte-rendu Entretien'), ('observation', 'Observation Terrain')], max_length=20),
        ),
        migrations.AlterField(
            model_name='isocontrol',
            name='category',
            field=models.CharField(choices=[('politique', 'Politique de Securite'), ('organisation', 'Organisation de la Securite'), ('rh', 'Securite des RH'), ('actifs', 'Gestion des Actifs'), ('acces', "Controle d'Acces"), ('cryptographie', 'Cryptographie'), ('physique', 'Securite Physique'), ('operations', 'Securite Operationnelle'), ('communications', 'Securite des Communications'), ('incidents', 'Gestion des Incidents'), ('continuite', "Continuite d'Activite"), ('conformite', 'Conformite')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='difficulty',
            field=models.CharField(choices=[('debutant', 'Debutant'), ('intermediaire', 'Intermediaire'), ('avance', 'Avance')], default='intermediaire', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='sector',
            field=models.CharField(choices=[('hopital', 'Hopital / Sante'), ('ecommerce', 'E-Commerce'), ('entreprise', 'Entreprise de Services'), ('banque', 'Banque / Finance'), ('industrie', 'Industrie / Manufacturing')], max_length=50),
        ),
    ]
