from django.core.management.base import BaseCommand
from audit_app.models import Scenario, ISOControl, ScenarioControl, Evidence

ISO_CONTROLS = [
    {'code': 'A.5.1',  'norm': '27002', 'category': 'politique',
     'title': "Politiques de securite de l'information",
     'description': "Un ensemble de politiques de securite doit etre defini, approuve par la direction, publie et communique a tous les employes.",
     'objective': "Fournir des orientations et un soutien de la direction pour la securite de l'information.",
     'guidance': "Verifier l'existence d'une politique ecrite, sa date de revision et sa communication effective."},
    {'code': 'A.5.2',  'norm': '27002', 'category': 'politique',
     'title': "Roles et responsabilites en securite",
     'description': "Toutes les responsabilites en matiere de securite doivent etre definies et attribuees.",
     'objective': "Etablir un cadre clair de gouvernance de la securite.",
     'guidance': "Verifier l'organigramme securite, les fiches de poste et la designation d'un RSSI."},
    {'code': 'A.5.3',  'norm': '27002', 'category': 'organisation',
     'title': "Separation des taches",
     'description': "Les taches et domaines de responsabilite incompatibles doivent etre separes.",
     'objective': "Reduire les risques de modification non autorisee ou involontaire.",
     'guidance': "Verifier que les personnes n'ont pas a la fois des droits de creation et d'approbation sur un meme processus."},
    {'code': 'A.6.1',  'norm': '27002', 'category': 'rh',
     'title': "Securite avant l'embauche",
     'description': "Les verifications des antecedents des candidats doivent etre realisees avant l'embauche.",
     'objective': "S'assurer que les employes sont aptes a exercer leur role.",
     'guidance': "Verifier les procedures de verification d'identite, de diplomes et de casier judiciaire."},
    {'code': 'A.6.2',  'norm': '27002', 'category': 'rh',
     'title': "Sensibilisation, education et formation",
     'description': "Tous les employes doivent recevoir une formation appropriee a la securite de l'information.",
     'objective': "Garantir que le personnel est conscient de ses responsabilites.",
     'guidance': "Verifier les programmes de formation, leur frequence, et les attestations de completion."},
    {'code': 'A.7.1',  'norm': '27002', 'category': 'actifs',
     'title': "Inventaire des actifs",
     'description': "Les actifs associes a l'information doivent etre identifies et un inventaire tenu a jour.",
     'objective': "Identifier les actifs et definir les responsabilites de protection.",
     'guidance': "Examiner le registre des actifs, sa completude, sa mise a jour et les proprietaires designes."},
    {'code': 'A.7.2',  'norm': '27002', 'category': 'actifs',
     'title': "Classification de l'information",
     'description': "L'information doit etre classifiee selon les exigences legales, la valeur et la sensibilite.",
     'objective': "Assurer un niveau de protection approprie a chaque information.",
     'guidance': "Verifier l'existence d'une politique de classification et son application concrete."},
    {'code': 'A.8.1',  'norm': '27002', 'category': 'acces',
     'title': "Politique de controle d'acces",
     'description': "Une politique de controle d'acces doit etre etablie et documentee.",
     'objective': "Limiter l'acces a l'information et aux installations.",
     'guidance': "Verifier la politique d'acces, le principe du moindre privilege et les revues d'acces periodiques."},
    {'code': 'A.8.2',  'norm': '27002', 'category': 'acces',
     'title': "Gestion des identifiants d'acces",
     'description': "Un processus formel d'enregistrement et de desinscription des utilisateurs doit exister.",
     'objective': "Permettre et revoquer les acces de facon formelle et tracee.",
     'guidance': "Verifier les procedures d'onboarding/offboarding et les logs de creation/suppression de comptes."},
    {'code': 'A.8.3',  'norm': '27002', 'category': 'acces',
     'title': "Gestion des droits d'acces privileges",
     'description': "L'attribution et l'utilisation des droits d'acces privileges doivent etre limitees et controlees.",
     'objective': "Empecher les abus de privileges administrateurs.",
     'guidance': "Verifier le nombre de comptes admin, leur justification, le MFA et les logs d'utilisation."},
    {'code': 'A.8.5',  'norm': '27002', 'category': 'acces',
     'title': "Authentification securisee",
     'description': "Des mesures d'authentification securisee doivent controler l'acces aux systemes.",
     'objective': "Empecher les acces non autorises aux systemes et applications.",
     'guidance': "Verifier la complexite des mots de passe, le MFA sur les systemes critiques et les politiques de blocage."},
    {'code': 'A.8.7',  'norm': '27002', 'category': 'operations',
     'title': "Protection contre les logiciels malveillants",
     'description': "Des mesures de detection et de prevention des malwares doivent etre deployees.",
     'objective': "Proteger les systemes contre les logiciels malveillants.",
     'guidance': "Verifier la presence d'antivirus, leur mise a jour, et la politique de protection sur les endpoints."},
    {'code': 'A.8.8',  'norm': '27002', 'category': 'operations',
     'title': "Gestion des vulnerabilites techniques",
     'description': "Les vulnerabilites techniques doivent etre identifiees et corrigees dans des delais definis.",
     'objective': "Empecher l'exploitation des vulnerabilites.",
     'guidance': "Verifier le processus de patch management, les scans de vulnerabilites et les delais de correction."},
    {'code': 'A.8.9',  'norm': '27002', 'category': 'operations',
     'title': "Gestion des configurations",
     'description': "Les configurations des systemes doivent etre etablies, documentees et maintenues.",
     'objective': "Assurer la securite des configurations et eviter les derives.",
     'guidance': "Verifier l'existence de baselines de configuration et les processus de gestion des changements."},
    {'code': 'A.8.11', 'norm': '27002', 'category': 'operations',
     'title': "Suppression des donnees",
     'description': "Les donnees stockees dans les systemes doivent etre supprimees de facon securisee.",
     'objective': "Empecher la divulgation non autorisee d'informations lors de la cession de materiels.",
     'guidance': "Verifier les procedures d'effacement securise et de recyclage des supports."},
    {'code': 'A.8.12', 'norm': '27002', 'category': 'operations',
     'title': "Prevention de la fuite de donnees",
     'description': "Des mesures de prevention de fuite de donnees doivent etre appliquees.",
     'objective': "Detecter et prevenir la divulgation non autorisee d'informations sensibles.",
     'guidance': "Verifier la presence de solutions DLP et les politiques de transfert de donnees."},
    {'code': 'A.8.16', 'norm': '27002', 'category': 'incidents',
     'title': "Surveillance des activites",
     'description': "Les reseaux, systemes et applications doivent etre surveilles pour detecter les comportements anormaux.",
     'objective': "Detecter rapidement les incidents de securite.",
     'guidance': "Verifier la presence d'un SIEM, les regles de detection et le processus d'alerte."},
    {'code': 'A.8.24', 'norm': '27002', 'category': 'cryptographie',
     'title': "Utilisation de la cryptographie",
     'description': "Des regles doivent definir l'utilisation efficace de la cryptographie pour proteger l'information.",
     'objective': "Assurer la confidentialite, l'integrite et l'authenticite de l'information.",
     'guidance': "Verifier la politique crypto, les algorithmes utilises (AES-256, TLS 1.2+) et la gestion des cles."},
    {'code': 'A.5.29', 'norm': '27001', 'category': 'continuite',
     'title': "Securite de l'information en cas de perturbation",
     'description': "L'organisation doit planifier la continuite de la securite en cas d'incident ou de sinistre.",
     'objective': "Maintenir la securite lors des situations de crise.",
     'guidance': "Verifier le PCA/PRA, les tests de reprise et les RTO/RPO definis."},
    {'code': 'A.5.31', 'norm': '27001', 'category': 'conformite',
     'title': "Exigences legales, statutaires et contractuelles",
     'description': "Toutes les exigences legales et reglementaires doivent etre identifiees et documentees.",
     'objective': "Eviter les violations des obligations legales ou contractuelles.",
     'guidance': "Verifier la conformite RGPD, les contrats fournisseurs et la veille reglementaire."},
]

def e(title, etype, content, hint):
    return {'title': title, 'evidence_type': etype, 'content': content, 'hint': hint}

HOPITAL = {
    'A.5.1': [e("Politique Securite v2.1 - 2022", 'document',
        "POLITIQUE DE SECURITE - HOPITAL SAINT-LUC\nVersion : 2.1 | Date : 15/03/2022\n\nDocument non revise depuis 2022 (> 2 ans).\nLes services cloud adoptes en 2023 ne sont pas couverts.\nDiffusion limitee aux cadres de sante uniquement.\nLes soignants n'ont pas recu de communication officielle.", 'partiel')],
    'A.5.2': [e("Entretien DSI - Gouvernance Securite", 'interview',
        "Entretien 10/01/2024 - M. Dupont, DSI\n\nQ: Un RSSI est-il designe ?\nR: Non. La fonction RSSI est assuree par le responsable IT en plus de ses autres missions. Pas de lettre de mission formelle ni de budget dedie.\n\nQ: Des responsabilites securite sont-elles documentees ?\nR: Les fiches de poste mentionnent vaguement 'respect des regles de securite' mais il n'existe pas de matrice RACI securite.", 'non_conforme')],
    'A.5.3': [e("Rapport AD - Anomalies Separation Taches", 'log',
        "RAPPORT SEPARATION DES TACHES - 15/01/2024\n\nANOMALIES DETECTEES :\n- 3 infirmieres ont acces lecture ET ecriture sur les prescriptions medicales\n- L'admin systeme peut creer des comptes ET valider des acces\n- Aucune double validation pour acces aux donnees de recherche\n\nCONCLUSION : Principe de separation des taches non applique sur fonctions critiques.", 'non_conforme')],
    'A.6.1': [e("Procedure RH - Verification Antecedents", 'document',
        "PROCEDURE RECRUTEMENT - RH-003 | 2020\n\nVerification identite : Oui\nVerification diplomes : Sur declaration (non verifiee)\nCasier judiciaire : Non demande systematiquement\n\nNOTE : Aucune verification des antecedents pour les prestataires externes ayant acces au SIH. 12 prestataires actifs sans verification documentee.", 'partiel')],
    'A.6.2': [e("Plan de Formation Securite 2023", 'document',
        "PLAN DE FORMATION SECURITE - 2023\n\nSensibilisation RGPD : 1h e-learning (taux completion : 42%)\nGestion des mots de passe : Non realisee\nPhishing : Aucun exercice depuis 2021\n\nEntretien responsable formation : 'Nous manquons de temps et de budget. La sensibilisation securite n est pas une priorite face aux formations cliniques obligatoires.'", 'non_conforme')],
    'A.7.1': [e("Inventaire Actifs - CMDB Partielle", 'document',
        "INVENTAIRE ACTIFS - HOPITAL SAINT-LUC\nDerniere MaJ : Juillet 2022\n\nActifs recenses : 312 sur environ 450 estimes\nProprietaires designes : 60% des actifs critiques\nTerminaux mobiles : Non inventories (BYOD sans enregistrement)\nLogiciels medicaux tiers : Liste incomplete\n\nLACUNE : 18 mois sans mise a jour.", 'partiel')],
    'A.7.2': [e("Politique Classification Information", 'document',
        "POLITIQUE DE CLASSIFICATION - v1.0 - 2021\n\nNiveaux definis : Confidentiel Medical, Confidentiel Interne, Usage Interne\n\nCONSTAT :\n- Classification non appliquee sur les emails (aucun marquage)\n- Documents sur serveurs partages non classifies\n- Aucun controle automatique de classification\n- Sensibilisation au personnel : Non realisee", 'partiel')],
    'A.8.1': [e("Politique Controle Acces - v1.1", 'document',
        "POLITIQUE DE CONTROLE D'ACCES - v1.1 - Janvier 2023\n\nPrincipes declares : Moindre privilege, RBAC, Revue semestrielle\n\nRevue des acces realisee : NON (derniere revue : 2021)\nMatrice des roles documentee : OUI (partielle)\nPrincipe moindre privilege applique : NON\n\nEntretien DSI : 'On n a pas eu le temps de faire la revue cette annee.'", 'partiel')],
    'A.8.2': [e("Logs Active Directory - Comptes Inactifs", 'log',
        "RAPPORT COMPTES UTILISATEURS - AD HOPITAL\nDate : 15/01/2024\n\nComptes inactifs (> 90 jours) encore actifs : 47\n  - martin.b@saint-luc.fr | Depart : 01/06/2023 | Statut : ACTIF\n  - sophie.r@saint-luc.fr | Depart : 15/04/2023 | Statut : ACTIF\n\nComptes partages detectes : 3 (infirmiere_nuit, accueil1, labo_commun)\nDelai moyen desactivation depart : 21 jours (objectif : 24h)", 'non_conforme')],
    'A.8.3': [e("Rapport Comptes Privilegies", 'config',
        "AUDIT COMPTES ADMINISTRATEURS - 12/01/2024\n\nTotal comptes admin : 18\nMFA active : 6/18 (33%)\nComptes admin partages : 2 (admin_sih, admin_reseau)\nRotation mots de passe : Non automatisee\nSessions enregistrees : Non\n\nANOMALIES :\n- 4 comptes admin de prestataires externes encore actifs\n- 2 comptes admin sans connexion depuis 6 mois", 'non_conforme')],
    'A.8.5': [e("Configuration Authentification - Serveurs SIH", 'config',
        "AUDIT AUTHENTIFICATION - HOPITAL SAINT-LUC\n\nPOLITIQUE MOT DE PASSE :\n  Longueur minimum : 8 caracteres (ANSSI recommande : 12)\n  Blocage apres echecs : Non configure\n\nMFA :\n  VPN : Non\n  Applications metier : Non\n  Messagerie : Non\n  Aucun MFA deploye", 'non_conforme')],
    'A.8.7': [e("Rapport Protection Anti-Malware", 'config',
        "AUDIT PROTECTION ENDPOINTS - 08/01/2024\n\nAntivirus : Symantec Endpoint Protection\nTaux de couverture : 87% des postes (13% non proteges)\nDerniere MaJ signatures : J-3 sur 40% des postes\nProtection serveurs : Partielle (5 serveurs sans antivirus)\nProtection equipements medicaux connectes : Non (incompatibilite)\n\nRISQUE : Les 13% non couverts incluent 3 postes aux urgences.", 'partiel')],
    'A.8.8': [e("Scan Vulnerabilites - Janvier 2024", 'log',
        "SCAN VULNERABILITES - HOPITAL\nOutil : Nessus | Date : 08/01/2024\n\nCritiques : 4\n  - CVE-2023-44487 (HTTP/2 Reset) | PATCH NON APPLIQUE\n  - CVE-2022-41082 (ProxyNotShell) | PATCH NON APPLIQUE (6 mois)\n  - CVE-2023-4966 (Citrix Bleed) | PATCH NON APPLIQUE\n\nDelai moyen correction patches critiques : 45 jours (objectif : 72h)\nDernier pentest : Novembre 2021 (26 mois)", 'non_conforme')],
    'A.8.9': [e("Audit Configuration Serveurs", 'config',
        "AUDIT CONFIGURATION BASELINE - 09/01/2024\n\nBaseline de securite definie : Non\nDurcissement OS (CIS Benchmark) : Non applique\nPorts ouverts non justifies : 23 detectes\nServices inutiles actifs : 8 serveurs\nGestion des changements : Informelle (email DSI)\n\nCONSTAT : Absence de gestion formelle des configurations.\nChaque administrateur applique ses propres pratiques.", 'non_conforme')],
    'A.8.11': [e("Procedure Gestion Fin de Vie Materiels", 'document',
        "PROCEDURE CESSION MATERIELS - IT-007 | 2019\n\nEffacement disques : Formatage simple (non securise)\nCertification effacement : Non realisee\n\nCONSTAT :\n- Formatage simple insuffisant (donnees recuperables)\n- 3 postes recemment cedes sans trace d'effacement\n- Aucun outil certifie utilise\n- Donnees patients potentiellement recuperables", 'non_conforme')],
    'A.8.12': [e("Audit Prevention Fuite Donnees", 'observation',
        "OBSERVATION TERRAIN - DLP - 10/01/2024\n\nOutil DLP : Non\nControle USB : Non (USB libres sur tous les postes)\nControle impression : Non\nTransfert cloud : Non controle\nEmail sortant : Non surveille\n\nINCIDENTS RECENTS :\n- Janvier 2024 : Fichier patients envoye a adresse externe (non detecte)\n- Decembre 2023 : Cle USB perdue contenant listes de patients", 'non_conforme')],
    'A.8.16': [e("Infrastructure de Surveillance - Etat des Lieux", 'config',
        "AUDIT SURVEILLANCE ET JOURNALISATION - 11/01/2024\n\nSIEM deploye : Non\nCentralisation des logs : Partielle\nRetention des logs : 30 jours (RGPD recommande : 1 an)\nAnalyse des logs : Manuelle, ponctuelle\nAlertes automatiques : Non\nSOC : Aucun\n\nLogs disponibles :\n  Pare-feu : Oui (non analyses)\n  AD : Oui (non centralises)\n  Applications metier : Non", 'non_conforme')],
    'A.8.24': [e("Rapport Chiffrement Infrastructure", 'config',
        "AUDIT CRYPTOGRAPHIE - HOPITAL SAINT-LUC\n\nBASE DE DONNEES PATIENTS (DPI) :\n  Chiffrement au repos : Non\n  Chiffrement en transit : TLS 1.2 sur 70% des flux\n\nSAUVEGARDES :\n  Chiffrement : AES-256 sur les bandes\n  Cles chiffrement : Fichier Excel sur partage reseau (RISQUE)\n\nVPN acces distant : Non deploye\nEmail : Non chiffre\nResultats patients par email : Non chiffres", 'non_conforme')],
    'A.5.29': [e("Plan de Continuite d'Activite - v3.0", 'document',
        "PCA - HOPITAL SAINT-LUC | Version 3.0 | Juin 2023\n\nRTO SIH : 4 heures | RPO : 1 heure\n\nINFRASTRUCTURE DE REPRISE :\n  Site secondaire : Meme batiment (RISQUE SINISTRE MAJEUR)\n  Site distant : Non\n\nTESTS PCA :\n  Dernier test : Mars 2023\n  RTO reel obtenu : 6h30 (objectif 4h NON ATTEINT)\n  Plan de remediation : 'En cours'", 'partiel')],
    'A.5.31': [e("Tableau Conformite Reglementaire", 'document',
        "CONFORMITE REGLEMENTAIRE - HOPITAL SAINT-LUC | Janvier 2024\n\nRGPD :\n  DPO nomme : Oui (depuis 2018)\n  Registre des traitements : Partiel (60% des traitements)\n  DPIA : 2 sur 8 requises realisees\n  Notifications CNIL : 1 en 2023 (dans les delais)\n\nHDS : Certification hebergeur : Oui\n\nLACUNES :\n  - 6 DPIA non realisees\n  - Registre des traitements incomplet", 'partiel')],
}

ECOMMERCE = {
    'A.5.1': [e("Politique Securite - Approuvee CODIR Mars 2024", 'document',
        "POLITIQUE DE SECURITE - BOUTIQUESHOP | Version 2.0 | Mars 2024\n\nApprouvee par : Directeur General (signature)\nProchaine revue : Mars 2025\nPerimetre : Site web, ERP, CRM, outils collaboratifs, cloud\n\nCommunication :\n- Diffusee a tous les employes (Mars 2024) avec accuse de reception\n- Formation obligatoire : 1h/an (taux completion : 94%)\n- Affichee sur l'intranet\n\nAxes prioritaires : MFA, chiffrement donnees clients, reponse incidents", 'conforme')],
    'A.5.2': [e("Organigramme Securite et Fiches de Poste", 'document',
        "GOUVERNANCE SECURITE - BOUTIQUESHOP\n\nRSSI : Nomme formellement depuis Jan 2023 (lettre de mission signee DG)\nRattachement : Direction Generale\nBudget securite : 5% du budget IT\nComite Securite : Trimestriel (RSSI + DSI + DG + DPO)\n\nResponsabilites :\n- Matrice RACI securite : Oui, mise a jour trimestrielle\n- Fiches de poste : Mention explicite des responsabilites securite\n- DPO nomme et declare CNIL : Oui", 'conforme')],
    'A.5.3': [e("Audit Separation des Taches", 'config',
        "AUDIT SEPARATION DES TACHES - 10/01/2024\n\nEnvironnements :\n  Production isole du developpement : Oui\n  Acces direct prod par les devs : Non (bastion obligatoire)\n  Deploiement prod : Via CI/CD avec validation tech lead\n\nFonctions financieres :\n  Validation paiements : Double signature (montants > 1000 EUR)\n  Creation fournisseur + validation paiement : Personnes distinctes\n\nCONSTAT : Separation des taches globalement respectee.", 'conforme')],
    'A.6.1': [e("Procedure Recrutement et Verification Antecedents", 'document',
        "PROCEDURE RECRUTEMENT - RH-001 | v2.0 | 2023\n\nVerification identite : Systematique (CNI/passeport)\nVerification diplomes : Aupres des etablissements pour postes techniques\nCasier judiciaire B3 : Pour postes sensibles\nReferences professionnelles : 2 references verifiees\nPrestataires : Meme procedure + assurance RC + NDA avant acces\n\nCONFORMITE : Procedure appliquee sur les 8 recrutements 2023.", 'conforme')],
    'A.6.2': [e("Rapport Formation Securite 2023", 'document',
        "PROGRAMME FORMATION - BOUTIQUESHOP 2023\n\nTest phishing : 3 campagnes | Taux de clic : 8% (vs 15% en 2022)\nFormation RGPD : 2h e-learning | Taux completion : 97%\nFormation dev securite (OWASP Top 10) : 4h equipe dev\nSensibilisation generale : 1h/an tous employes | Taux : 94%\n\nAttestations conservees dans les dossiers RH.", 'conforme')],
    'A.7.1': [e("CMDB BoutiqueShop - Actifs Critiques", 'document',
        "CMDB BOUTIQUESHOP - MaJ : 10/01/2024\n\nCOUVERTURE : 98% des actifs identifies\nProprietaires designes : 100% actifs critiques\nRevue : Trimestrielle (derniere : Decembre 2023)\n\nActifs critiques tous documentes avec proprietaires designes.\n\nLACUNE MINEURE : Outils SaaS personnels (shadow IT) non tous references.\nAudit shadow IT prevu T1 2024.", 'partiel')],
    'A.7.2': [e("Politique Classification et Application", 'document',
        "CLASSIFICATION - BOUTIQUESHOP | v1.1 | Septembre 2023\n\nNiveaux : CONFIDENTIEL, INTERNE, PUBLIC\nApplication : Marquage obligatoire sur les emails niveau CONFIDENTIEL\nTemplates documents avec bandeau classification\nChamps BDD marques selon classification\n\nFormation : Septembre 2023 (96% des employes formes)\nControle : Audit trimestriel de conformite au marquage", 'conforme')],
    'A.8.1': [e("Politique Controle Acces - v1.2", 'document',
        "POLITIQUE CONTROLE D'ACCES - v1.2 | Janvier 2024\n\nPrincipes :\n  Moindre privilege : Applique et documente\n  RBAC : 5 profils definis\n  MFA : Obligatoire sur VPN, back-office, outils cloud\n\nRevue des acces : Semestrielle\nDerniere revue : Decembre 2023 (3 acces revoques)\n\nNON-CONFORMITE : ERP sans MFA (deploiement prevu T1 2024)", 'partiel')],
    'A.8.2': [e("Processus Onboarding-Offboarding IT", 'document',
        "PROCEDURE GESTION ACCES - IT-002 | v2.1 | 2023\n\nONBOARDING :\n  Formulaire signe par le manager : Oui\n  Delai creation compte : 24h avant arrivee\n\nOFFBOARDING :\n  Notification IT par RH le jour de la decision : Oui\n  Desactivation compte : Dans les 2h\n  Checklist 12 applications SaaS validee\n\nAUDIT Decembre 2023 :\n  Comptes inactifs >60j : 0\n  Anciens prestataires actifs : 0", 'conforme')],
    'A.8.3': [e("Gestion Comptes Privilegies - PAM", 'config',
        "RAPPORT ACCES PRIVILEGIES - 12/01/2024\n\nComptes admin : 8 | MFA : 8/8 (100%)\nComptes personnels (non partages) : 8/8\nRotation mots de passe : Automatique 60 jours\nEnregistrement sessions admin : Oui (outil Teleport)\nAcces prod par bastion : Obligatoire\nRevue mensuelle comptes admin : Oui", 'conforme')],
    'A.8.5': [e("Configuration Authentification - Extrait", 'config',
        "AUDIT AUTHENTIFICATION - BOUTIQUESHOP - 10/01/2024\n\nPOLITIQUE MOT DE PASSE :\n  Longueur min : 14 caracteres\n  Complexite : Activee\n  Historique : 12 derniers\n  Blocage : 5 tentatives => verrouillage 15 min\n\nMFA DEPLOYE : VPN, back-office, outils cloud\nNON DEPLOYE : ERP (en cours, T1 2024)\n\nRemarque : ERP sans MFA = ecart mineur, plan d'action documente.", 'partiel')],
    'A.8.7': [e("Protection Anti-Malware - Configuration", 'config',
        "AUDIT PROTECTION ENDPOINTS - 09/01/2024\n\nAntivirus : CrowdStrike Falcon (EDR cloud-based)\nCouverture : 100% postes et serveurs\nMise a jour : Automatique en temps reel\nProtection email : Proofpoint + sandboxing\nScan images Docker : Via CI/CD (Trivy)\n\nIncidents 2023 : 3 alertes malware, neutralisees automatiquement.\nAucun incident malware n'a atteint la production.", 'conforme')],
    'A.8.8': [e("Scan Vulnerabilites - Janvier 2024", 'log',
        "SCAN VULNERABILITES - BOUTIQUESHOP\nDate : 08/01/2024\n\nCritiques : 2\n  - CVE-2023-44487 (HTTP/2 Reset) | PATCH NON APPLIQUE\n  - CVE-2023-4966 (Citrix Bleed) | PATCH NON APPLIQUE\n\nDelai patches critiques : Objectif 72h | Reel : ~15 jours (NON CONFORME)\nDernier pentest : Novembre 2022 (14 mois)", 'non_conforme')],
    'A.8.9': [e("Baselines de Configuration", 'document',
        "GESTION DES CONFIGURATIONS - BOUTIQUESHOP\n\nBaselines definies :\n  Serveurs Linux : CIS Benchmark Level 1 (applique)\n  Nginx : Configuration durcie OWASP\n  Docker : Best practices enforces via linting\n\nGestion des changements :\n  CAB mensuel : Oui\n  Configuration as Code : Terraform + Ansible (versionne)\n  Drift detection : Terraform Cloud (alertes automatiques)", 'conforme')],
    'A.8.11': [e("Procedure Effacement Securise", 'document',
        "PROCEDURE SUPPRESSION DONNEES - IT-009 | v1.1 | 2023\n\nEffacement disques : DBAN (certifie DoD 5220.22-M)\nCertificat d'effacement : Genere et archive\nDroit a l'effacement RGPD : Procedure automatisee (SLA 30j)\nCloud AWS : Chiffrement + zero-fill avant suppression\n\nCONFORMITE : Procedure complete, auditee trimestriellement.", 'conforme')],
    'A.8.12': [e("Solution DLP - Rapport Deploiement", 'config',
        "PREVENTION FUITE DONNEES - BOUTIQUESHOP\nSolution : Microsoft Purview DLP | Deploye Octobre 2023\n\nPolitiques actives :\n  Email sortant : Detection donnees CB, emails clients => blocage\n  OneDrive/SharePoint : Detection fichiers clients sensibles\n  Impression : Documents CONFIDENTIEL => alerte manager\n\nStatistiques Janvier 2024 :\n  Incidents detectes : 4\n  Blocages automatiques : 2\n  Violations reelles : 0", 'conforme')],
    'A.8.16': [e("Infrastructure SIEM - Tableau de Bord", 'config',
        "SURVEILLANCE - BOUTIQUESHOP\n\nSIEM : Elastic SIEM (deploye Mars 2023)\nSources centralises : 12 sources de logs\nRegles detection : 47 regles actives (MITRE ATT&CK)\nAlertes critiques : PagerDuty => astreinte DSI (24/7)\n\nSOC externe : SecureOps (SLA 1h)\nRetention logs : 1 an\n\nIncidents detectes 2023 : 12 alertes, 3 confirmes, 0 violation.", 'conforme')],
    'A.8.24': [e("Audit Chiffrement - BoutiqueShop.fr", 'config',
        "AUDIT CHIFFREMENT - BOUTIQUESHOP - 10/01/2024\n\nSITE WEB : TLS 1.3 | Grade A (SSL Labs)\nBASE CLIENTS : Chiffrement AES-256 au repos\nMOTS DE PASSE : bcrypt (cost factor 12)\nDONNEES CB : Tokenisees via Stripe (PCI-DSS)\nSAUVEGARDES : AES-256, AWS S3 Paris, test restauration trimestriel\nGESTION CLES : HashiCorp Vault, rotation annuelle automatique", 'conforme')],
    'A.5.29': [e("Plan de Reprise Activite - v2.1", 'document',
        "PCA/PRA - BOUTIQUESHOP | v2.1 | Octobre 2023\n\nOBJECTIFS :\n  RTO site e-commerce : 2 heures\n  RPO : 1 heure (sauvegardes horaires)\n\nINFRASTRUCTURE :\n  Multi-region AWS : Paris (principal) + Francfort (reprise)\n  Bascule automatique : Route53 health checks\n\nTESTS 2023 :\n  Test bascule region : Septembre 2023 | RTO reel : 1h20 (OK)\n  Test restauration : Novembre 2023 (OK)", 'conforme')],
    'A.5.31': [e("Tableau Conformite Reglementaire", 'document',
        "CONFORMITE REGLEMENTAIRE - BOUTIQUESHOP | Janvier 2024\n\nRGPD :\n  DPO : Nomme (externe, cabinet specialise)\n  Registre traitements : Complet (18 traitements)\n  DPIA : 3 realisees\n  Notifications CNIL : 1 en 2023 (dans les 72h)\n\nPCI-DSS : Non certifie (tokenisation Stripe = hors perimetre)\nVeille reglementaire : Abonnement CNIL + cabinet juridique", 'conforme')],
}

FINTECH = {
    'A.5.1': [e("Politique Securite Groupe - v4.0", 'document',
        "POLITIQUE DE SECURITE - SECUREPAY SA\nVersion : 4.0 | Janvier 2024\n\nApprouvee par : DG + CA\nBudget securite : 12% du budget IT\nRevue : Annuelle (Janvier 2024)\n\nCommunication : Tous employes + prestataires critiques\nFormation obligatoire a l'embauche et rappel annuel\n\nConformite declaree : ISO 27001 (en cours), PCI-DSS, DORA, RGPD", 'conforme')],
    'A.5.2': [e("Gouvernance Securite - Organigramme", 'document',
        "GOUVERNANCE SECURITE - SECUREPAY SA\n\nCISO : Membre du COMEX, rattache au Directoire\nBudget : Autonome, vote par le CA\nComite Securite : Mensuel\n\nStructure :\n  CISO\n  |-- Responsable SOC (5 analystes 24/7)\n  |-- Responsable GRC\n  |-- Responsable Architecture Securite\n  |-- Red Team (2 pentesters internes)\n\nMatrice RACI complete, mise a jour semestrielle.", 'conforme')],
    'A.5.3': [e("Audit Separation des Taches - Finance et SI", 'config',
        "SEPARATION DES TACHES - SECUREPAY - 12/01/2024\n\nTRANSACTIONS :\n  Creation ordre : Equipe Operations\n  Validation ordre : Equipe Finance (distincte)\n  Rapprochement : Audit Interne (distinct)\n\nSI :\n  Dev : Aucun acces production\n  Admin BDD prod : 2 DBA dedicaces (double validation)\n  Cles chiffrement : HSM, acces M-of-N (3/5 personnes)\n\nCONFORMITE : Separation rigoureuse, auditee trimestriellement.", 'conforme')],
    'A.6.1': [e("Procedure Verification Antecedents", 'document',
        "PROCEDURE RECRUTEMENT - RH-CRIT-001 | v3.0 | 2023\n\nPOSTES CRITIQUES :\n  Casier judiciaire B3 : Obligatoire\n  3 derniers emplois : Verifies\n  Diplomes : Systematique\n  Credit check : Pour acces flux financiers\n\nPRESTATAIRES : Meme niveau + assurance RC + NDA\nREVERIFICATION : Tous les 3 ans pour postes critiques\n\nCONFORMITE : 100% recrutements 2023 selon procedure.", 'conforme')],
    'A.6.2': [e("Programme Formation et Sensibilisation 2023", 'document',
        "FORMATION SECURITE - SECUREPAY 2023\n\nFormation a l'embauche : 8h (obligatoire + evaluation)\nSensibilisation annuelle : 4h (taux : 100%)\nDev : Secure coding OWASP 16h/an\nExercices : Test phishing mensuel (taux clic : 3%)\nSimulation incident : Trimestriel\nRed team : 2 exercices par an\n\nCertifications : CISSP, CISM financement 100%", 'conforme')],
    'A.7.1': [e("CMDB ServiceNow - Actifs Critiques", 'document',
        "CMDB SECUREPAY - MaJ : 10/01/2024\n\nCOUVERTURE : 99% des actifs\nProprietaires : 100% actifs critiques\nRevue : Mensuelle pour actifs critiques\n\nDependances cartographiees : Oui\nShadow IT : Politique interdiction SaaS non approuves + scan mensuel\n\nActifs critiques : Gateway Paiement, Core Banking, HSM - tous documentes", 'conforme')],
    'A.7.2': [e("Politique Classification et Schema Base", 'document',
        "CLASSIFICATION - SECUREPAY | v2.0 | 2023\n\nNiveaux : STRICTEMENT CONFIDENTIEL, CONFIDENTIEL, INTERNE, PUBLIC\n\nApplication technique :\n  Champs BDD marques selon classification\n  Controles d'acces bases sur la classification\n  DLP aligne sur les niveaux\n  Audit automatique mensuel\n\nConformite ACPR : Classification alignee sur exigences prudentielles.", 'conforme')],
    'A.8.1': [e("Politique Controle Acces - v5.0 - Zero Trust", 'document',
        "CONTROLE D'ACCES - SECUREPAY | v5.0 | 2024\n\nArchitecture Zero Trust : Deployee\nMFA : Obligatoire sur 100% des acces (aucune exception)\nAcces conditionnel : Azure AD Conditional Access\n\nRevue :\n  Comptes privilegies : Mensuelle\n  Comptes standards : Trimestrielle\n  Prestataires : A chaque renouvellement de contrat\n\nDerniere revue : Janvier 2024 (5 acces revoques)", 'conforme')],
    'A.8.2': [e("Processus IAM - Rapport Conformite", 'config',
        "GESTION IDENTITES - SECUREPAY\nOutil : SailPoint IGA | Janvier 2024\n\nONBOARDING : Acces provisiones automatiquement selon role\nOFFBOARDING : Notification SIRH automatique, desactivation < 1h\n\nSTATISTIQUES :\n  Comptes inactifs > 30j : 0\n  Comptes orphelins : 0\n  Recertification Janvier 2024 : 100% complete", 'conforme')],
    'A.8.3': [e("PAM CyberArk - Rapport Acces Privilegies", 'config',
        "GESTION ACCES PRIVILEGIES - SECUREPAY\nSolution : CyberArk | Janvier 2024\n\nComptes privilegies : 23 | MFA : 23/23 (100%)\nAcces Just-in-Time : 23/23 (100%)\nSessions enregistrees : 100%\nRotation auto mots de passe : 24h\nCoffre-fort secrets : CyberArk Vault (aucun mdp en dur dans le code)\n\nScore maturite PAM : 4.8/5 (evaluation externe 2023)", 'conforme')],
    'A.8.5': [e("Configuration Authentification Zero Trust", 'config',
        "AUTHENTIFICATION - SECUREPAY - 10/01/2024\n\nMot de passe : 16 caracteres minimum + gestionnaire 1Password obligatoire\nMFA : 100% des acces (FIDO2/WebAuthn pour acces critiques)\nApplications paiement : Cle physique YubiKey\nAPI partenaires : mTLS (certificats mutuels)\n\nAuthentification continue : UEBA (User Entity Behavior Analytics)", 'conforme')],
    'A.8.7': [e("Protection Malware - Infrastructure Paiement", 'config',
        "PROTECTION ANTI-MALWARE - SECUREPAY\n\nEDR : CrowdStrike Falcon (tous endpoints et serveurs) | Couverture : 100%\nIsolation auto endpoint compromis : Active\nWAF : Cloudflare (regles OWASP + regles metier)\nScan SAST/DAST : Chaque pipeline CI/CD\n\nAUCUN INCIDENT MALWARE en 2023 ayant atteint la production.", 'conforme')],
    'A.8.8': [e("Vulnerability Management Program", 'log',
        "PROGRAMME GESTION VULNERABILITES - SECUREPAY | Janvier 2024\n\nSCAN CONTINU : Tenable.io (scan continu, 100% infrastructure)\n\nRESULTATS :\n  Critiques : 0 en attente (traitement <= 24h)\n  Hautes : 2 en cours (dans le SLA de 72h)\n\nPENTEST :\n  Externe : 2 par an (dernier : Novembre 2023)\n  Bug Bounty : Programme actif HackerOne (12 vulns payees 2023)", 'conforme')],
    'A.8.9': [e("Infrastructure as Code - Gestion Config", 'config',
        "GESTION DES CONFIGURATIONS - SECUREPAY\n\nInfrastructure as Code : Terraform 100% cloud, Ansible serveurs\nBaseline : CIS Benchmark Level 2 sur tous les serveurs\nVerification : Automatique via pipeline (echec = blocage deploiement)\nDrift detection : Hebdomadaire\n\nGestion changements :\n  CAB hebdomadaire : Oui\n  Zero changement manuel en production : Politique stricte", 'conforme')],
    'A.8.11': [e("Politique Suppression Donnees - v2.0", 'document',
        "SUPPRESSION SECURISEE - SECUREPAY\n\nDONNEES CLIENTS :\n  Retention : 5 ans (ACPR) puis purge automatique\n  Effacement RGPD : SLA 72h, process automatise\n\nMATERIELS :\n  Effacement : NIST SP 800-88 certifie\n  Certificat destruction : Archive 5 ans\n\nCloud : Cle chiffrement detruite avant restitution volume\n\nCONFORMITE : Validee par DPO et ACPR.", 'conforme')],
    'A.8.12': [e("DLP Programme - Bilan 2023", 'config',
        "PREVENTION FUITE DONNEES - SECUREPAY\nSolution : Microsoft Purview + Nightfall AI\n\nPerimetre couvert : Email, cloud storage, endpoints, API sortantes\n\nStatistiques 2023 :\n  Incidents detectes : 28\n  Blocages automatiques : 19\n  Violations reelles : 0\n\nRevue mensuelle des politiques DLP par le CISO.", 'conforme')],
    'A.8.16': [e("SOC et SIEM - Rapport Operationnel", 'config',
        "SOC ET SURVEILLANCE - SECUREPAY\n\nSIEM : Splunk Enterprise Security | Sources : 127 sources de logs\nRetention : 2 ans | EPS : 45 000 evenements/seconde\n\nSOC INTERNE : 24/7/365 (5 analystes, 3 niveaux)\nMTTR P1 : < 15 minutes | MTTD P1 : < 5 minutes\n\nRegles detection : 312 regles MITRE ATT&CK\n\nINCIDENTS 2023 : 3 incidents P1, 0 violation de donnees.", 'conforme')],
    'A.8.24': [e("Architecture Cryptographique - v3.0", 'config',
        "CRYPTOGRAPHIE - SECUREPAY | Audit Janvier 2024\n\nHSM : 2 Thales Luna Network (actif-actif, FIPS 140-2 L3)\nAlgorithmes : AES-256-GCM, RSA-4096, SHA-256, TLS 1.3\n\nGESTION DES CLES :\n  Cycle de vie : Documente et automatise\n  Rotation : Annuelle (auto via HSM)\n  Sauvegarde : M-of-N (3 sur 5 personnes)\n\nCONFORMITE : PCI-DSS P2PE certifie.", 'conforme')],
    'A.5.29': [e("Plan Resilience Operationnelle - DORA", 'document',
        "PCA RESILIENCE - SECUREPAY | v5.0 | Decembre 2023 | Aligne DORA\n\nOBJECTIFS :\n  RTO Gateway : 15 minutes | RPO : 0 (replication synchrone)\n  Disponibilite : 99.999% (tenu en 2023 : 99.9997%)\n\nARCHITECTURE :\n  Multi-cloud Actif-Actif : AWS Paris + Azure Paris\n  Basculement automatique : < 30 secondes (teste)\n\nTESTS DORA 2023 : Bascule multi-cloud (RTO reel : 8 min)\nRapport DORA soumis ACPR dans les delais.", 'conforme')],
    'A.5.31': [e("Tableau Conformite Reglementaire Complet", 'document',
        "CONFORMITE REGLEMENTAIRE - SECUREPAY | Janvier 2024\n\nDORA : En cours | PCI-DSS v4.0 : Certifie L1\nRGPD : Conforme | NIS2 : Gap analysis en cours\nACPR 97-02 : Conforme | ISO 27001 : Certification en cours\n\nVeille : ANSSI, ACPR, CNIL, FS-ISAC\nJuriste externe : Cabinet specialise fintech\n\nPOINT ATTENTION : NIS2 - plan de conformite non encore finalise.", 'partiel')],
}

PME = {
    'A.5.1': [e("Politique Securite - Brouillon non approuve", 'document',
        "POLITIQUE DE SECURITE - TECHCONSULT (BROUILLON)\nStatut : NON APPROUVE | Redaction : En cours depuis 6 mois\n\nCe document n'a jamais ete presente a la Direction.\n\nContenu actuel : Quelques regles basiques mots de passe et emails.\n\nMANQUES :\n- Pas de classification des informations\n- Pas de gouvernance definie\n- Pas d'engagement de la direction\n- Non communique aux employes\n\nEntretien DG : 'Je n'ai pas encore vu ce document.'", 'non_conforme')],
    'A.5.2': [e("Entretien Direction - Gouvernance Securite", 'interview',
        "Entretien 08/01/2024 - Mme Martin, Directrice Generale\n\nQ: Un RSSI est-il designe ?\nR: 'Non. C'est notre responsable IT qui gere ca en plus du reste. Pas de mission formelle.'\n\nQ: La securite est-elle abordee en CODIR ?\nR: 'Honnement non. C'est pour ca qu'on fait cet audit.'\n\nQ: Avez-vous un budget dedie securite ?\nR: 'Non, on prend sur le budget IT general quand il y a un besoin.'", 'non_conforme')],
    'A.5.3': [e("Observation - Separation des Taches", 'observation',
        "OBSERVATION TERRAIN - SEPARATION DES TACHES\nDate : 09/01/2024\n\nCONSTAT :\n1. Le responsable IT peut creer des comptes, valider des achats ET acceder a toutes les donnees sans controle.\n2. 3 developpeurs ont acces direct BDD production ('plus pratique pour deboguer').\n3. La comptable peut creer des fournisseurs ET valider des paiements.\n\nAucune procedure de double validation pour les actions sensibles.", 'non_conforme')],
    'A.6.1': [e("Procedure Recrutement - Etat des Lieux", 'document',
        "PROCEDURE RECRUTEMENT - TECHCONSULT\nEtat actuel (entretien RH, 08/01/2024)\n\nVerification identite : Oui (CNI)\nVerification diplomes : Sur declaration uniquement\nCasier judiciaire : Non demande\nAccord de confidentialite : Non systematique\n\nPrestataires avec acces donnees clients :\n2 prestataires freelances ont acces au CRM sans NDA signe.\n\nCONCLUSION : Aucune procedure formelle de verification.", 'non_conforme')],
    'A.6.2': [e("Formation Securite - Etat des Lieux", 'interview',
        "Entretien Responsable IT - 08/01/2024\n\nQ: Des formations securite sont-elles realisees ?\nR: 'Non. J'envoie des emails parfois quand il y a une alerte phishing dans l'actualite.'\n\nQ: Les employes savent-ils reconnaitre un email de phishing ?\nR: 'Probablement pas tous. On a eu un incident en 2023.'\n\nQ: Y a-t-il un programme de sensibilisation ?\nR: 'Non, c'est prevu mais pas mis en place.'", 'non_conforme')],
    'A.7.1': [e("Inventaire Actifs - Fichier Excel Obsolete", 'document',
        "INVENTAIRE ACTIFS - TECHCONSULT.xlsx\nRetrouve sur un poste de travail (pas de version centralisee)\nDerniere modification : Juillet 2022\n\nPROBLEMES :\n- 18 mois sans mise a jour\n- Aucune classification\n- Donnees clients des projets non repertoriees\n- Outils SaaS non listes (Notion, Slack, Teams, GitHub)\n- Aucun proprietaire designe\n- Actifs acquis en 2023 non dans l'inventaire", 'non_conforme')],
    'A.7.2': [e("Classification Information - Absence de Politique", 'observation',
        "OBSERVATION TERRAIN - CLASSIFICATION\nDate : 09/01/2024\n\nAucune politique de classification n'existe.\n\nCONSTATS :\n- Documents clients et supports marketing dans le meme dossier partage\n- Aucun marquage sur les documents\n- Livrables clients partages via WeTransfer sans chiffrement\n- Code source de projets clients sur GitHub PUBLIC\n  (incident decouvert lors de l'audit - client non averti)", 'non_conforme')],
    'A.8.1': [e("Controle d'Acces - Observation", 'observation',
        "OBSERVATION TERRAIN - CONTROLE D'ACCES\nDate : 09/01/2024\n\nCONSTATS :\n- Tous les employes ont acces a tous les dossiers du serveur partage\n- Acces CRM : Ouvert a 100% des employes (y compris comptabilite)\n- Revue des acces : Jamais realisee\n- Politique d'acces formelle : Inexistante\n\nLe principe du moindre privilege n'est pas applique.", 'non_conforme')],
    'A.8.2': [e("Gestion Comptes - Observation Terrain", 'observation',
        "OBSERVATION TERRAIN - GESTION DES COMPTES\nDate : 09/01/2024\n\nOFFBOARDING - Dernier depart (Novembre 2023) :\n- Compte Windows : Supprime apres 3 semaines\n- Acces Salesforce : Encore ACTIF (2 mois apres depart)\n- Acces GitHub : Encore ACTIF\n- Acces Notion : Encore ACTIF\n\nPas de checklist. Pas de procedure documentee.\n\nONBOARDING : 'On envoie un email a l'IT et ca se fait.'", 'non_conforme')],
    'A.8.3': [e("Comptes Administrateurs - Etat des Lieux", 'config',
        "AUDIT COMPTES PRIVILEGIES - TECHCONSULT\nDate : 09/01/2024\n\nComptes admin Windows : 6 (objectif : 2 maximum)\n\nParmi les 6 admin :\n- 4 developpeurs ont des droits admin 'par confort'\n- 1 compte admin generique 'admin_techconsult' partage\n- Mots de passe admin : Sur post-it dans un tiroir commun\n\nMFA sur comptes admin : Non\nLogs utilisation admin : Non", 'non_conforme')],
    'A.8.5': [e("Politique Mots de Passe - Etat des Lieux", 'config',
        "AUDIT AUTHENTIFICATION - TECHCONSULT - 09/01/2024\n\nAucune politique formelle de mots de passe.\n\nCONSTAT TERRAIN :\n- Mots de passe simples observes : 'techconsult2023', 'admin123'\n- Partage de mots de passe entre collegues : Confirme\n- Gestionnaire de mots de passe : Non (notes papier, fichier Excel)\n- Renouvellement : Jamais (sauf oubli)\n- MFA : Non deploye sur aucun service\n\nPOST-IT avec mots de passe sur 2 postes observes.", 'non_conforme')],
    'A.8.7': [e("Protection Malware - Etat des Lieux", 'config',
        "AUDIT PROTECTION ENDPOINTS - TECHCONSULT - 09/01/2024\n\nAntivirus : Windows Defender (non gere centralement)\nMises a jour : Manuelles (pas toujours faites)\nServeur : Sans antivirus\nProtection email : Filtre spam basique\n\nINCIDENT 2023 :\nUn poste infecte par malware apres phishing.\nDetection : 4 jours plus tard (par hasard).\nImpact : Acces CRM pendant 4 jours.\n\nAucune procedure de reponse aux incidents documentee.", 'non_conforme')],
    'A.8.8': [e("Vulnerabilites - Absence de Gestion", 'observation',
        "AUDIT GESTION VULNERABILITES - TECHCONSULT\n\nScan de vulnerabilites : Jamais realise\nPatch management : Informel ('quand on y pense')\n\nCONSTATS TERRAIN :\n- Serveur principal : Windows Server 2012 R2 (fin de support 2023)\n- 3 postes non mis a jour depuis 8 mois\n- WordPress v5.9 (version actuelle : 6.4) avec plugins obsoletes vulnerables\n\nAucune veille sur les vulnerabilites.", 'non_conforme')],
    'A.8.9': [e("Documentation Technique - Etat des Lieux", 'interview',
        "Entretien Responsable IT - 08/01/2024\n\nQ: Les configurations sont-elles documentees ?\nR: 'J'ai quelques notes sur Confluence mais pas structure. C'est surtout dans ma tete.'\n\nQ: Qu'arriverait-il si vous etiez absent 2 semaines ?\nR: 'Ca serait complique... Personne d'autre ne sait.'\n\nBUS FACTOR = 1 : Dependance totale a une seule personne.\n\nAucune procedure documentee pour : sauvegardes, incidents, acces en cas d'absence.", 'non_conforme')],
    'A.8.11': [e("Suppression Donnees - Pratiques Observees", 'observation',
        "OBSERVATION - SUPPRESSION DES DONNEES\nDate : 09/01/2024\n\nMATERIELS RECYCLES :\n- 2 anciens ordinateurs donnes sans effacement\n- 1 disque dur 'formate' (formatage simple, donnees recuperables)\n\nDONNEES CLIENTS :\n- Anciens projets jamais supprimes (projets depuis 2015)\n- Aucune politique de retention documentee\n\nRGPD :\n- Aucune procedure de traitement des demandes d'effacement\n- 1 demande recue en 2023 sans reponse formelle", 'non_conforme')],
    'A.8.12': [e("Fuite Donnees - Incidents et Pratiques", 'observation',
        "OBSERVATION - PREVENTION FUITE DONNEES\nDate : 09/01/2024\n\nOutil DLP : Aucun\nControle USB : Aucun | Controle emails : Aucun\nPartage fichiers : WeTransfer, Google Drive personnel non controles\n\nINCIDENTS IDENTIFIES LORS DE L'AUDIT :\n1. Code source projet client sur repo GitHub PUBLIC\n2. Fichier Excel contacts clients partage via lien Google Drive ouvert\n3. Developpeur a copie BDD de test (vraies donnees) sur poste personnel\n\nRISQUE RGPD ELEVE : Plusieurs violations potentielles non declarees.", 'non_conforme')],
    'A.8.16': [e("Surveillance - Absence de Moyens", 'interview',
        "Entretien Responsable IT - 08/01/2024\n\nQ: Avez-vous des outils de surveillance de votre SI ?\nR: 'On a les logs Windows mais je ne les consulte jamais vraiment.'\n\nQ: Avez-vous detecte des tentatives d'intrusion ?\nR: 'Je n'en sais rien, je n'ai pas les outils pour le voir.'\n\nQ: Les logs sont-ils centralises ?\nR: 'Non. Et je pense qu'ils sont ecrases apres quelques jours.'\n\nCONCLUSION : Aucun SIEM. Logs non centralises. Aucune capacite de detection.", 'non_conforme')],
    'A.8.24': [e("Chiffrement - Pratiques Actuelles", 'config',
        "AUDIT CRYPTOGRAPHIE - TECHCONSULT - 09/01/2024\n\nSITE WEB : HTTPS Oui | Grade SSL Labs : B (protocoles obsoletes actifs)\n\nSERVEUR INTERNE :\n  Chiffrement disques : Non\n  Chiffrement sauvegardes : Non\n  Protocoles internes : SMB non chiffre, HTTP interne\n\nEMAILS :\n  Chiffrement : Non\n  Livrables clients : Envoyes non chiffres par email\n\nMots de passe sensibles : Fichier Excel non chiffre partage", 'non_conforme')],
    'A.5.29': [e("Continuite d'Activite - Etat des Lieux", 'interview',
        "Entretien Responsable IT - 08/01/2024\n\nQ: Avez-vous un Plan de Continuite d'Activite ?\nR: 'Non. On sauvegarde les donnees mais pas de plan formel.'\n\nQ: Comment sont faites les sauvegardes ?\nR: 'J'ai un disque dur externe que je branche le vendredi soir. Enfin, quand je n'oublie pas.'\n\nQ: Avez-vous teste la restauration ?\nR: 'Non, jamais. J'espere que ca marche.'\n\nQ: Que se passe-t-il si le serveur tombe en panne ?\nR: 'On attend que je le repare. Ca peut prendre 2-3 jours.'", 'non_conforme')],
    'A.5.31': [e("Conformite Reglementaire - Etat des Lieux", 'interview',
        "Entretien DG + Responsable IT - 08/01/2024\n\nRGPD :\nQ: Avez-vous un DPO ou registre des traitements ?\nDG: 'On n'a pas de DPO. Je ne sais pas ce qu'est un registre des traitements.'\n\nINCIDENTS RGPD identifies lors de l'audit :\n- Code client sur GitHub public : Violation non declaree\n- Donnees sur Drive public : Violation non declaree\n\nCONTRATS :\n- Aucune clause RGPD dans les contrats prestataires\n- Pas de DPA (Data Processing Agreement)\n\nRISQUE : Exposition importante aux sanctions CNIL.", 'non_conforme')],
}

SCENARIOS_DATA = [
    {
        'meta': {
            'title': 'Audit SMSI - Hopital Regional Saint-Luc',
            'sector': 'hopital', 'difficulty': 'avance', 'sector_icon': 'HOP',
            'company_name': 'Hopital Saint-Luc', 'company_size': '850 employes, 400 lits',
            'description': 'Audit de conformite ISO 27001 d un hopital regional gerant des donnees medicales sensibles, confronte a des cybermenaces croissantes.',
            'company_context': "L Hopital Saint-Luc est un centre hospitalier regional dispose d un SIH centralise, d un PACS pour l imagerie medicale et de nombreux terminaux connectes. L etablissement est soumis aux exigences HDS et RGPD. Suite a une cyberattaque par ransomware dans un hopital voisin, la direction a decide de faire auditer son SMSI.",
            'audit_objective': "Evaluer la conformite du SMSI aux exigences ISO 27001 et 27002 avec focus sur la protection des donnees medicales, la gestion des acces, la continuite d activite et la surveillance.",
            'is_active': True,
        },
        'evidences': HOPITAL,
    },
    {
        'meta': {
            'title': 'Audit SMSI - BoutiqueShop (E-Commerce)',
            'sector': 'ecommerce', 'difficulty': 'intermediaire', 'sector_icon': 'EC',
            'company_name': 'BoutiqueShop SAS', 'company_size': '45 employes, 500k clients',
            'description': 'Audit de conformite ISO 27001/27002 d une PME e-commerce en cours de certification, gerant des donnees clients et de paiement.',
            'company_context': "BoutiqueShop est une PME francaise specialisee dans la vente en ligne de produits de mode. Apres un incident de scraping en 2023, elle cherche a obtenir la certification ISO 27001 pour rassurer ses clients et partenaires.",
            'audit_objective': "Evaluer la maturite de la securite de BoutiqueShop en vue de sa certification ISO 27001 avec focus sur la protection des donnees clients, la gestion des vulnerabilites et la reponse aux incidents.",
            'is_active': True,
        },
        'evidences': ECOMMERCE,
    },
    {
        'meta': {
            'title': 'Audit SMSI - SecurePay (Fintech)',
            'sector': 'banque', 'difficulty': 'avance', 'sector_icon': 'BQ',
            'company_name': 'SecurePay SA', 'company_size': '200 employes, agree ACPR',
            'description': 'Audit de conformite ISO 27001 d une fintech de paiement soumise a la reglementation ACPR et DORA, traitant 2M de transactions par jour.',
            'company_context': "SecurePay est une fintech agreee ACPR specialisee dans les solutions de paiement B2B traitant 2 millions de transactions par jour. Elle doit demonstrer une resilience operationnelle conforme a DORA.",
            'audit_objective': "Verifier la conformite ISO 27001 et l alignement DORA de SecurePay avec focus sur la resilience operationnelle, la securite des paiements et la gestion des risques.",
            'is_active': True,
        },
        'evidences': FINTECH,
    },
    {
        'meta': {
            'title': 'Audit a blanc - TechConsult SARL (PME)',
            'sector': 'entreprise', 'difficulty': 'debutant', 'sector_icon': 'ENT',
            'company_name': 'TechConsult SARL', 'company_size': '80 employes',
            'description': 'Premier audit ISO 27001 a blanc d une PME de conseil IT. Scenario debutant avec des non-conformites claires et identifiables.',
            'company_context': "TechConsult est une PME de conseil en transformation digitale gerant des donnees clients confidentielles. Face a des appels d offres exigeant ISO 27001, elle entame son premier audit pour identifier ses ecarts.",
            'audit_objective': "Realiser un audit a blanc ISO 27001 pour identifier les ecarts. Scenario debutant : la quasi-totalite des controles presentent des non-conformites claires et evidentes a identifier.",
            'is_active': True,
        },
        'evidences': PME,
    },
]


class Command(BaseCommand):
    help = 'Populate database with 20 ISO controls and 4 complete scenarios (no emojis)'

    def handle(self, *args, **options):
        self.stdout.write('Suppression des donnees existantes...')
        Evidence.objects.all().delete()
        ScenarioControl.objects.all().delete()
        Scenario.objects.all().delete()
        ISOControl.objects.all().delete()

        self.stdout.write('Creation des 20 controles ISO...')
        ctrl_map = {}
        for cd in ISO_CONTROLS:
            c = ISOControl.objects.create(**cd)
            ctrl_map[c.code] = c
        self.stdout.write(self.style.SUCCESS(f'  {len(ISO_CONTROLS)} controles crees'))

        self.stdout.write('Creation des 4 scenarios...')
        for sd in SCENARIOS_DATA:
            scenario = Scenario.objects.create(**sd['meta'])
            ev_dict = sd['evidences']
            for order, code in enumerate(ctrl_map.keys()):
                ctrl = ctrl_map[code]
                sc = ScenarioControl.objects.create(scenario=scenario, control=ctrl, order=order)
                for ev_data in ev_dict.get(code, []):
                    Evidence.objects.create(scenario_control=sc, **ev_data)
            ctrl_count = scenario.scenario_controls.count()
            self.stdout.write(f'  Scenario "{scenario.company_name}" : {ctrl_count} controles')

        self.stdout.write(self.style.SUCCESS('\nTermine ! Lancez ensuite : python manage.py createsuperuser'))
